services:
  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  authentik-proxy:
    image: ghcr.io/goauthentik/proxy
    environment:
      AUTHENTIK_HOST: $AUTHENTIK_HOST
      AUTHENTIK_INSECURE: "true"
      AUTHENTIK_TOKEN: $AUTHENTIK_TOKEN
      AUTHENTIK_DEBUG: "true"
    labels:
      traefik.enable: true
      traefik.port: 9000
      traefik.http.routers.proxy.rule: Host(`$TRAEFIK_HOST`) && PathPrefix(`/outpost.goauthentik.io`)
      traefik.http.middlewares.authentik.forwardauth.address: http://authentik-proxy:9000/outpost.goauthentik.io/auth/traefik
      traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authentik.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-aut>
    restart: unless-stopped
    networks:
      - backend

  postgres:
    image: postgres:12.2
    volumes:
      - postgres_data:/data/postgres
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: /data/postgres
    networks:
      - backend
    ports:
      - "5432:5432"
    restart: always

  bookings:
    image: ghcr.io/logefrei/logefrei-back:main
    networks:
      - backend
    depends_on:
      - postgres
      - authentik-proxy
    environment:
      SERVICE: bookings
      DATABASE_URL: $DATABASE_URL
      PORT: 3000
    labels:
      traefik.enable: true
      traefik.http.routers.bookings.rule: Host(`$TRAEFIK_HOST`) && PathPrefix(`/api/bookings`)
      traefik.http.routers.bookings.middlewares: authentik
      traefik.http.services.booking.loadbalancer.server.port: 3000

  search:
    image: ghcr.io/logefrei/logefrei-back:main
    networks:
      - backend
    depends_on:
      - postgres
      - authentik-proxy
    environment:
      SERVICE: search
      DATABASE_URL: $DATABASE_URL
      PORT: 3000
    labels:
      traefik.enable: true
      traefik.http.routers.search.rule: Host(`$TRAEFIK_HOST`) && PathPrefix(`/api/search`)
      traefik.http.routers.search.middlewares: authentik
      traefik.http.services.search.loadbalancer.server.port: 3000

  housings:
    image: ghcr.io/logefrei/logefrei-back:main
    networks:
      - backend
    depends_on:
      - postgres
      - authentik-proxy
    environment:
      SERVICE: housings
      DATABASE_URL: $DATABASE_URL
      PORT: 3000
    labels:
      traefik.enable: true
      traefik.http.routers.housings.rule: Host(`$TRAEFIK_HOST`) && PathPrefix(`/api/housings`)
      traefik.http.routers.housings.middlewares: authentik
      traefik.http.services.housings.loadbalancer.server.port: 3000

  users:
    image: ghcr.io/logefrei/logefrei-back:main
    networks:
      - backend
    depends_on:
      - postgres
      - authentik-proxy
    environment:
      SERVICE: users
      DATABASE_URL: $DATABASE_URL
      PORT: 3000
    labels:
      traefik.enable: true
      traefik.http.routers.users.rule: Host(`$TRAEFIK_HOST`) && PathPrefix(`/api/users`)
      traefik.http.routers.users.middlewares: authentik
      traefik.http.services.users.loadbalancer.server.port: 3000

  background:
    image: ghcr.io/logefrei/logefrei-back:main
    environment:
      SERVICE: background
      DATABASE_URL: $DATABASE_URL
    networks:
      - backend

  front:
    image: ghcr.io/logefrei/logefrei-front:main
    networks:
      - backend
    labels:
      traefik.enable: true
      traefik.http.routers.front.rule: Host(`$TRAEFIK_HOST`)
      traefik.http.routers.front.entrypoints: web
      traefik.http.services.front.loadbalancer.server.port: 3000
      traefik.http.routers.front.middlewares: authentik

networks:
  backend:

volumes:
  postgres_data:
