FROM oven/bun AS build

WORKDIR /app

COPY . .

ENV NODE_ENV=production

RUN bun install --frozen-lockfile

RUN bunx prisma generate
RUN bun run compile

FROM debian:bullseye-slim

WORKDIR /app

# For healthcheck
RUN apt-get update && apt-get install -y curl

COPY --from=build /app/app app
COPY --from=build /app/node_modules/.prisma node_modules/.prisma

EXPOSE 3000

CMD [ "./app" ]