# syntax=docker/dockerfile:1.4

ARG NODE_VERSION=18.14.2

FROM node:${NODE_VERSION}-slim as base

ENV NODE_ENV=development

WORKDIR /src

FROM base as build

COPY --link package.json package-lock.json ./
RUN npm install

FROM base

COPY --from=build /src/node_modules /src/node_modules

CMD [ "npm", "run", "dev" ]