ARG NODE_IMAGE=oven/bun

FROM $NODE_IMAGE AS base
WORKDIR /home/bun/app

FROM base AS install

RUN mkdir -p /temp
COPY package.json bun.lockb /temp/
RUN cd /temp && bun install --frozen-lockfile

FROM install AS dev

COPY --from=install /temp/node_modules /home/bun/app/node_modules
COPY . .

ENV HOST=0.0.0.0
ENV NODE_ENV=development
EXPOSE 3000

ENTRYPOINT [ "bun", "run", "dev" ]